apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webapp
  description: web application
  annotations:
    github.com/project-slug: mankinimbom/maven
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: development
  lifecycle: experimentation
